// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQWJ3z_NRTixseFeIaXgn5iWeUSpEhBwc',
    appId: '1:902106432119:web:0779e7b52af997a2907c72',
    messagingSenderId: '902106432119',
    projectId: 'otp-verification-d0033',
    authDomain: 'otp-verification-d0033.firebaseapp.com',
    storageBucket: 'otp-verification-d0033.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTCBKS6GOPOXFA-LTyF2YS8-NmVLhYQNc',
    appId: '1:902106432119:android:e2cb1fc097dfffc1907c72',
    messagingSenderId: '902106432119',
    projectId: 'otp-verification-d0033',
    storageBucket: 'otp-verification-d0033.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdvWHnFf5sBOHeooq3mu_8_U3T8mESq8A',
    appId: '1:902106432119:ios:c0c2b5d6ed34bcca907c72',
    messagingSenderId: '902106432119',
    projectId: 'otp-verification-d0033',
    storageBucket: 'otp-verification-d0033.appspot.com',
    iosBundleId: 'com.example.otpVerification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdvWHnFf5sBOHeooq3mu_8_U3T8mESq8A',
    appId: '1:902106432119:ios:c0c2b5d6ed34bcca907c72',
    messagingSenderId: '902106432119',
    projectId: 'otp-verification-d0033',
    storageBucket: 'otp-verification-d0033.appspot.com',
    iosBundleId: 'com.example.otpVerification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQWJ3z_NRTixseFeIaXgn5iWeUSpEhBwc',
    appId: '1:902106432119:web:ff44ce450005d681907c72',
    messagingSenderId: '902106432119',
    projectId: 'otp-verification-d0033',
    authDomain: 'otp-verification-d0033.firebaseapp.com',
    storageBucket: 'otp-verification-d0033.appspot.com',
  );
}
